server:
  port: 8081
spring:
  application:
    name: eureka_server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: false

  server:
    enable-self-preservation: false

